################################################
#### DOCKER-COMPOSE GITHUB  Hetimop/swarm01 ####
################################################

services:
  cadvisor:
    container_name: cadvisor_solo
    restart: unless-stopped
    userns_mode: host
    image: grc.io/cadvisor/cadvisor:v0.47.1
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/50000000.50000000:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
      - "8080:8080"
    networks:
      - metrics
    logging:
        driver: syslog
        options:
            syslog-facility: "local4"
            tag: "{{.Name}}/{{.ID}}"
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 1

networks:
  metrics:
    driver: bridge
