################################################
#### DOCKER-COMPOSE DEPLOYE AVEC ANSIBLE M2 ####
############### VIA GITLAB-FORGE ###############
################################################

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 780t:9100
          - vm1055:9100
          - vm1056:9100
          - vm1057:9100

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 780t:8080
          - vm1055:8080
          - vm1056:8080
          - vm1057:8080
      
  - job_name: 'dockerd'
    static_configs:
      - targets:
          - 780t:9323
          - vm1055:9323
          - vm1056:9323
          - vm1057:9323
      