################################################
#### DOCKER-COMPOSE GITHUB  Hetimop/swarm01 ####
################################################


version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./config-prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention=40d'
    ports:
      - 9090:9090
    networks:
      - metrics_swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == vm1055-swarm01]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2048M
          cpus: "1"
        reservations:
          memory: 128M

networks:
  metrics_swarm:
    driver: overlay
    attachable: true

volumes:
  prometheus_data:

